export { default as Error } from './error/Error'
export { default as GameEnd } from './gameEnd/GameEnd'
export { default as CompleteGrid } from './grid/CompleteGrid/CompleteGrid'
export { default as Header } from './header/Header'
export { default as Keyboard } from './keyboard/Keyboard'
export { default as StartInfo } from './startInfo/StartInfo'
export { default as Switch } from './switch/Switch'